version: '3.12'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_students
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: student
      POSTGRES_DB: students_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
